---
title: "Trends in different race incarceration rates"
output: html_document
---

### Introduction

I was curious after reading this data how the race and rate of incarceration were related over time. I think this is an important question to ask because so many of our protests today are about things like "Systemic Racism," and this would provide additional evidence to prooving these claims or ideas. I'm not saying that these claims are not already backed by evidence, but I wanted to try and plot it for myself. It's always been a passion of mine to persue organization in our claims. So that's what excited me about doing this project of Different Race Incarceration Rates over Time. We are looking specifically at the races given in the data: LatinX, Black, White, or Native. Note we won't be looking at the different areas, ages, genders, or any other data in regard to these people. By simply showing trends in their race and rate of incarceration, I hope to give some clarity on the trends.

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

These will likely be calculated using your DPLYR skills, answering questions such as: 

- What is the average value of my variable across all the counties (in the current year)?
- Where is my variable the highest / lowest?
- How much has my variable change over the last N years?

Feel free to calculate and report values that you find relevant. Again, remember that the purpose is to think about how these measure of incarceration vary by race.

### The Dataset

Who collected the data?
- The BJS. This includes the COJ and ASJ.

How was the data collected or generated?  
- ASJ collects data through surveys in 950 local jails. COJ collects data through census about 3200 local jails.

Why was the data collected?  
- These data were collected to estimate characteristics about inmates nationwide.

How many observations (rows) are in your data?
- 153811 rows

How many features (columns) are in the data?
- 121 columns

What, if any, ethical questions or questions of power do you need to consider when working with this data?
- I don't have any specific questions that come to mind besides: how did the take this census, and what is the margin for error? And: Were the innmates allowed to opt out of being counted if they want to?

What are possible limitations or problems with this data?   (at least 200 words)
- No matter what survey or census we take, we will never be able to represent the entire prison or jail or incarceration population. We don't know about factors like inmates being unwilling to be counted, or answering honestly about questions. This could result in inaccurate counting, which could result in inaccurate data collected through these means. Some other reasons the data could be inaccurate is that maybe some inmates are missed because of things like protective custody or solitary confinement. And because of the freedom to respond however they like, some inmates can be dishonest about themselves. We don't know for certain, therefore, if the data is accurate in regard to race, gender, or age, either. Some of this could be verified from the prison logs or manifest, yes, but the overall risk of misinformation as a result of the census is highly likely. A census in this respect is probably inaccurate, therefore, simply due to the lack of error margins, we have no clue what could be right, and what could be completely false. Finally there's the ethical side, where we can't force people to be a part of this study, we can't make anyone be a part of the count, and we can't ethically assume someone's gender, ethnicity, age, or the like. This means that the data we read needs to be taken with a grain of salt, since there's no way of getting 100% accuracy.


### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map
- Use a minimalist theme for the map 